# Site settings
title: Digital Solutions | Creengo
email: contact@creengo.com
url: https://www.creengo.com
description: "Creengo is a digital agency where clients can find digital solutions for their businesses."
skills: ""
meta_author: Creengo
header_title1: Connecting
header_title2: Ideas

# Google webmaster tools
google_verify: -z2afGwKwGyjAFuBqtPcR6hTze0yO2pyhrXqkDRHSx8

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: b4d7b2 #80B3FF
  primary-rgb: "180, 215, 178" #"128,179,255"
  secondary: 25282a #FD6E8A
  secondary-dark: 25282a #A2122F

# Footer settings
footer:
  copyright: Creengo
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/creengo
  - title: facebook
    url: https://facebook.com/creengo
  - title: github
    url: https://github.com/creengo

# Postal address (add as many lines as necessary)
address:
  - line: Spain
  - line: Europe

# Credits content
credits: 'Creengo'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
